### ISSUE TITLE
Change rest.css

### ISSUE THREAD

**Issue by vladanvi99** [calvnce/portfolio#9]
You wrote html,body,form,...{
    margin:0;
    padding:0;
    ...
}
Instead of it, you can put just *{
   margin:0;
   padding:0;
   ...
}
![issue](https://user-images.githubusercontent.com/67482737/122012133-1fbe2480-cdbd-11eb-8580-dc5e8a77f399.png)

**Comment by dami1080** [comment]
your code looks good and clean

**Comment by calvnce** [comment]
This is rest CSS
